services:
  grafenbot:
    container_name: grafenbot
    build:
      dockerfile: ./docker-build/Dockerfile
      context: .
    command: python3 run_bot.py
    restart: unless-stopped
    env_file:
      - ./src/.env
